- hosts: all
  remote_user: root
  tasks:
  - name: set project facts
    include: tasks/project-facts.yml

  - name: setup system packages
    include: tasks/system-setup.yml
  
  - name: create credentials directory
    include: tasks/credentials.yml
  
  - name: setup postgresql
    include: tasks/postgres.yml

  - name: setup project
    include: tasks/project.yml